---
kind: pipeline
name: x86

clone:
  depth: 10

platform:
  os: linux
  arch: amd64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:x86
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci:x86
    commands:
      - publish.sh x86
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST_KEY:
        from_secret: ssh_host_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: x86_64

clone:
  depth: 10

platform:
  os: linux
  arch: amd64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:x86_64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci:x86_64
    commands:
      - publish.sh x86_64
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST_KEY:
        from_secret: ssh_host_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: aarch64

clone:
  depth: 10

platform:
  os: linux
  arch: arm64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:aarch64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci:aarch64
    commands:
      - publish.sh aarch64
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST_KEY:
        from_secret: ssh_host_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: armhf

clone:
  depth: 10

platform:
  os: linux
  arch: arm

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:armhf
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci:armhf
    commands:
      - publish.sh armhf
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST_KEY:
        from_secret: ssh_host_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: armv7

clone:
  depth: 10

platform:
  os: linux
  arch: arm

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:armv7
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: github_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci:armv7
    commands:
      - publish.sh armv7
    environment:
      SSH_KEY:
        from_secret: ssh_key
      SSH_HOST_KEY:
        from_secret: ssh_host_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: announce

clone:
  disable: true

steps:
  - name: comment_pr
    image: gboo/github-pr
    settings:
      github_token:
        from_secret: algitbot_token
      action: comment
      message: |
        Build artifacts are uploaded. You can add the following url to your /etc/apk/repositories file
        http://ua.alpinelinux.org/packages/${DRONE_PULL_REQUEST}
    when:
      event: pull_request

depends_on:
  - x86
  - x86_64
  - armhf
  - armv7
  - aarch64

---
kind: signature
hmac: fb0480117986339e398cef43b5d3c83cebe44172b11c621613d65002a3d2615d

...
