---
kind: pipeline
name: edge-x86

clone:
  depth: 10

platform:
  os: linux
  arch: amd64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-x86
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci-publish:x86
    commands:
      - publish.sh
    environment:
      SSH_KEY:
        from_secret: ssh_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: edge-x86_64

clone:
  depth: 10

platform:
  os: linux
  arch: amd64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-x86_64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci-publish:x86_64
    commands:
      - publish.sh
    environment:
      SSH_KEY:
        from_secret: ssh_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: edge-aarch64

clone:
  depth: 10

platform:
  os: linux
  arch: arm64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-aarch64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci-publish:aarch64
    commands:
      - publish.sh
    environment:
      SSH_KEY:
        from_secret: ssh_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: edge-armhf

clone:
  depth: 10

platform:
  os: linux
  arch: arm

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-armhf
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci-publish:armhf
    commands:
      - publish.sh
    environment:
      SSH_KEY:
        from_secret: ssh_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: edge-armv7

clone:
  depth: 10

platform:
  os: linux
  arch: arm

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-armv7
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
      ABUILD_PRIV_KEY:
        from_secret: abuild_privkey
      ABUILD_PUB_KEY:
        from_secret: abuild_pubkey
    privileged: false
    pull: always
  - name: publish
    image: clandmeter/alpine-drone-ci-publish:armv7
    commands:
      - publish.sh
    environment:
      SSH_KEY:
        from_secret: ssh_key
      MQTT_PASS:
        from_secret: mqtt_pass

trigger:
  event:
    - pull_request

---
kind: pipeline
name: announce

clone:
  disable: true

steps:
  - name: comment_pr
    image: gboo/github-pr
    settings:
      github_token:
        from_secret: algitbot_token
      action: comment
      message: |
        Build artifacts are uploaded. You can add the following url to your /etc/apk/repositories file
        http://ua.alpinelinux.org/packages/${DRONE_REPO}/${DRONE_PULL_REQUEST}
    when:
      event: pull_request

depends_on:
  - edge-x86
  - edge-x86_64
  - edge-armhf
  - edge-armv7
  - edge-aarch64

---
kind: signature
hmac: fb0480117986339e398cef43b5d3c83cebe44172b11c621613d65002a3d2615d

...
