---
kind: pipeline
name: abuild

clone:
  depth: 10

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: clandmeter/abuild:latest
    privileged: false
    pull: always

trigger:
  event:
    - pull_request

