---
kind: pipeline
name: edge-x86

clone:
  depth: 50

platform:
  os: linux
  arch: amd64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-x86
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: pipeline
name: edge-x86_64

clone:
  depth: 50

platform:
  os: linux
  arch: amd64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-x86_64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: pipeline
name: edge-aarch64

clone:
  depth: 50

platform:
  os: linux
  arch: arm64

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-aarch64
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: pipeline
name: edge-armhf

clone:
  depth: 50

platform:
  os: linux
  arch: arm

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-armhf
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: pipeline
name: edge-armv7

clone:
  depth: 50

platform:
  os: linux
  arch: arm

workspace:
  base: /home/buildozer/drone
  path: aports

steps:
  - name: build
    image: clandmeter/alpine-drone-ci:edge-armv7
    commands:
      - build.sh
    environment:
      GH_TOKEN:
        from_secret: algitbot_token
    pull: always

trigger:
  event:
    - pull_request

---
kind: signature
hmac: fb0480117986339e398cef43b5d3c83cebe44172b11c621613d65002a3d2615d

...
